In [1]:
import nashpy as nash
import numpy as np

In [2]:
A = np.array([[0, 1, -1],
              [-1, 0, 1],
              [1, -1, 0]])
B = np.array([[0, -1, 1],
              [1, 0, -1],
              [-1, 1, 0]])
coordination_game = nash.Game(A, B)
coordination_game

Zero sum game with payoff matrices:

Row player:
[[ 0  1 -1]
 [-1  0  1]
 [ 1 -1  0]]

Column player:
[[ 0 -1  1]
 [ 1  0 -1]
 [-1  1  0]]

In [3]:
equilibria = coordination_game.vertex_enumeration()
for eq in equilibria:
    print(eq)

(array([0.33333333, 0.33333333, 0.33333333]), array([0.33333333, 0.33333333, 0.33333333]))
