In [1]:
import nashpy as nash 
import numpy as np 

In [2]:
M_A = np.array([[1.5, 1.0, 0.25, -0.75],
                [1.5, 1.25, 0.75, 0],
                [1.65, 1.15, 0.15, -0.35]])

M_B = np.array([[0, 0.25, 0.5, 0.25],
                [0, 0, 0, -0.5],
                [0, 0.25, 0.75, 0]])

game_selection = nash.Game(M_A, M_B)
game_selection

Bi matrix game with payoff matrices:

Row player:
[[ 1.5   1.    0.25 -0.75]
 [ 1.5   1.25  0.75  0.  ]
 [ 1.65  1.15  0.15 -0.35]]

Column player:
[[ 0.    0.25  0.5   0.25]
 [ 0.    0.    0.   -0.5 ]
 [ 0.    0.25  0.75  0.  ]]

In [3]:
equilibria = game_selection.vertex_enumeration()
for eq in equilibria:
    print(eq)

(array([0., 1., 0.]), array([2.08166817e-17, 0.00000000e+00, 1.00000000e+00, 0.00000000e+00]))
(array([0., 1., 0.]), array([-2.77555756e-17,  1.00000000e+00, -5.55111512e-17,  0.00000000e+00]))
(array([0., 1., 0.]), array([0.8, 0. , 0.2, 0. ]))
(array([0., 1., 0.]), array([ 4.00000000e-01,  6.00000000e-01,  0.00000000e+00, -5.82867088e-17]))
